
spring.jpa.show-sql=true
stripe.api.key=sk_test_51SjjXKJ6ZZBcPg42ZPODCKaaqdAQCWOvwIykHMBrrxnvWsv3Awxyqrc0TowUm31DVQbbvIVCAptqAoIvFdifxKqD0021hzRTcr
# Configuration SMTP pour Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# L'email que tu as choisi (celui qui enverra les messages)
spring.mail.username=ton-email-choisi@gmail.com

# ATTENTION : Ce n'est pas ton mot de passe habituel !
# C'est un "Mot de passe d'application" généré par Google.
spring.mail.password=xxxx-xxxx-xxxx-xxxx

# Propriétés de sécurité obligatoires
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:mariadb://mysql-1a8b396-emmanuelkouassi340-4ffb.l.aivencloud.com:21792/defaultdb?sslMode=trust
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_PNejXdUd0i3dIRuOtLU
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate settings pour MariaDB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect