spring:
  application:
    name: SAE
  datasource:
    url: jdbc:mariadb://mysql-1a8b396-emmanuelkouassi340-4ffb.l.aivencloud.com:21792/defaultdb?sslMode=trust
    username: avnadmin
    password: AVNS_PNejXdUd0i3dIRuOtLU
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
stripe:
  api:
    key: ${STRIPE_API_KEY}